name: Auto Update Version

on:
  push:
    paths:
      - 'BLE_test/apk/app_v*.apk'  # 修正路径匹配实际APK位置

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Find Latest APK
        id: find-apk
        run: |
          LATEST_APK=$(ls -t BLE_test/apk/app_v*.apk | head -1)
          echo "最新APK文件: $LATEST_APK"
          VERSION=$(basename $LATEST_APK | grep -oP '\d+\.\d+\.\d+')  # 提取纯数字版本号（如 2.0.0）
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "LATEST_APK=$(basename $LATEST_APK)" >> $GITHUB_OUTPUT

      - name: Update version.json
        run: |
          echo '{
            "latest_version": "${{ steps.find-apk.outputs.VERSION }}",
            "download_url": "https://ruddyis.github.io/BLECradle.github.io/BLE_test/apk/${{ steps.find-apk.outputs.LATEST_APK }}",
            "release_notes": "自动更新版本信息"
          }' > BLE_test/version.json  # 修正路径

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add BLE_test/version.json
          git commit -m "chore: 自动更新版本至 ${{ steps.find-apk.outputs.VERSION }}"
          git push
