name: Auto Update Version

on:
  push:
    paths:
      - 'apk/app_v*.apk'  # 监听apk目录下的APK文件变更

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Find Latest APK
        id: find-apk
        run: |
          # 获取最新APK文件名（按时间排序）
          LATEST_APK=$(ls -t apk/app_v*.apk | head -1)
          echo "最新APK文件: $LATEST_APK"
          
          # 提取版本号（从文件名中匹配 vX.Y.Z）
          VERSION=$(echo $LATEST_APK | grep -oP 'v\d+\.\d+\.\d+')
          echo "提取版本号: $VERSION"
          
          # 输出变量供后续步骤使用
          echo "LATEST_APK=$LATEST_APK" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Update version.json
        run: |
          # 生成version.json内容
          echo '{
            "latest_version": "${{ steps.find-apk.outputs.VERSION }}",
            "download_url": "https://ruddyis.github.io/BLECradle.github.io/BLE_test/apk/${{ steps.find-apk.outputs.LATEST_APK }}",
            "release_notes": "自动更新版本信息"
          }' > version.json

          # 打印更新后的内容
          cat version.json

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add version.json
          git commit -m "chore: 自动更新版本至 ${{ steps.find-apk.outputs.VERSION }}"
          git push
